
SOLVER:
  IMS_PER_BATCH: 1

INPUT:
  SIZE_TRAIN: [800,600]

DATASETS:
  TRAIN: "/data/sport_1_small/"
  SHIFT: 0.0
  MAXRATION: 0.0
  ROTATION: 0.0

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: "/mnt/truenas/scratch/xingyu.liao/checkpoints/mnist_template"
